export const coreTableNames = [
  "projects",
  "settings",
  "agent_adapters",
  "sessions",
  "session_runs",
  "review_items",
  "decisions",
  "decision_versions",
  "work_items",
  "work_item_dependencies",
  "work_item_attempts",
  "context_sources",
  "evidence_snapshots",
  "context_items",
  "context_item_versions",
  "context_packages",
  "rules",
  "rule_versions",
  "jobs",
  "job_attempts",
  "activity_events",
  "audit_events",
  "outbox_events",
  "idempotency_keys"
] as const;
